### ISSUE TITLE
problem to get vbgmm module in python for concoct_refine

### ISSUE THREAD

**Issue by yuxiangtan** [chrisquince/STRONG#112]
Dear author,

In the concoct_refine, it need to import vbgmm. But I found it is not available from conda or pip, and it is not mentioned in the installation on how to get it. What can I do now?

Thank you!

Yuxiang

**Comment by Sebastien-Raguideau** [comment]
Dear Yuxiang,

I'm unsure why you would look at that in particular. During the install, Concoct is installed as part of the STRONG env.
vbgmm is part of Concoct and installed together with it. 

Your question must result from an issue, an error message? Can you explain why you try to import vbgmm? Did you activate the STRONG env before doing so?

Best,
Seb

**Comment by yuxiangtan** [comment]
Thank you for your reply.

In the manual guideline, there is no Concoct installation. I installed concoct from conda.
The error message is failed to import vbgmm in python. However, I could not find a way to install it.

I am assuming the concoct should be installed together with SPAdes in your auto installation?

Best,

**Comment by Sebastien-Raguideau** [comment]
Dear Yuxiang,

It's hidden but it is there. It is part of the conda env you install with :
`mamba env create -f conda_env.yaml`

Ok, to help me understand better, you need to tell me what command you used to get that error message. 
Another question is about the environment. Did you activate the STRONG env before with :
`conda activate STRONG`

Best,
Seb
