### ISSUE TITLE
Broken URLs in README

### ISSUE THREAD

**Issue by bph6212ln** [chrisquince/STRONG#131]
The URLs listed in the README for both the cogs database and the test run data are broken.
wget https://strongtest.s3.climb.ac.uk/Test.tar.gz
wget https://strongtest.s3.climb.ac.uk/rpsblast_cog_db.tar.gz

Attempts to access these documents results in:
`<Error>`
`<Code>NoSuchBucket</Code>`
`<BucketName>strongtest</BucketName>`
blah-blah
`</Error>`

**Comment by chrisquince** [comment]
We apologise for this, our s3 provider changed their system, we now have updated links for both of these:

wget https://microbial-metag-strong.s3.climb.ac.uk/rpsblast_cog_db.tar.gz

wget https://microbial-metag-strong.s3.climb.ac.uk/Test.tar.gz
